### ISSUE TITLE
endless recursive call for the method recurseForImages in class AbstractScanDetector

### ISSUE THREAD

**Issue by Marwenenit** [tledoux/scannedPdf#1]
Hello and thank you for your work,

I am having this endless call for this method for one of the PDF i tested with .. is there a fix for the issue or should i modify the code manually and add something as a counter??

Here is the code:

  void recurseForImages(PDResources resources, Predicate<DimensionInfo> predicate)
      throws IOException {
    for (COSName name : resources.getXObjectNames()) {
      if (resources.isImageXObject(name)) {
        DimensionInfo dimImage = lookupImage(resources, name);
        if (!predicate.test(dimImage)) {
          break;
        }
        continue;
      }
      PDXObject xobject = resources.getXObject(name);
      if (xobject instanceof PDFormXObject) {
        PDFormXObject form = (PDFormXObject) xobject;
        PDResources formResources = form.getResources();
        recurseForImages(formResources, predicate);
      }
    }
  }
  
  
  ALSO in an unrelated issue i think line number 79 in the same class :           return ((COSName) base).getName();
should be changed to           return ((COSName) filters).getName();
or i am i wrong.

Thank you

**Comment by tledoux** [comment]
@Marwenenit. Oups, seems I completely forgot our enquiries. Hope this commi will correct the points you rightly bring. Any sample would be very appreciate.
